/* Generated By:JJTree&JavaCC: Do not edit this line. EG2Constants.java */
package farf;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_PAREN = 7;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 8;
  /** RegularExpression Id. */
  int LET = 9;
  /** RegularExpression Id. */
  int IN = 10;
  /** RegularExpression Id. */
  int MAPTO = 11;
  /** RegularExpression Id. */
  int NI = 12;
  /** RegularExpression Id. */
  int ALIASES = 13;
  /** RegularExpression Id. */
  int MATCHERS = 14;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 15;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 16;
  /** RegularExpression Id. */
  int HEX_LITERAL = 17;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int GLOB = 22;
  /** RegularExpression Id. */
  int FQCN = 23;
  /** RegularExpression Id. */
  int METHOD_GLOB = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"{\"",
    "\"}\"",
    "\"let\"",
    "\"in\"",
    "\"->\"",
    "\"ni\"",
    "\"aliases\"",
    "\"matchers\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<GLOB>",
    "<FQCN>",
    "<METHOD_GLOB>",
    "\"=\"",
    "\";\"",
  };

}
