/* Generated By:JavaCC: Do not edit this line. EG2TreeConstants.java Version 5.0 */
package farf;

public interface EG2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTALIASSECTION = 2;
  public int JJTMATCHERSSECTION = 3;
  public int JJTALIAS = 4;
  public int JJTMATCHER = 5;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AliasSection",
    "MatchersSection",
    "Alias",
    "Matcher",
  };
}
/* JavaCC - OriginalChecksum=4af63ba70e7e365a84370849a2894860 (do not edit this line) */
