/* Generated By:JavaCC: Do not edit this line. EG2TreeConstants.java Version 5.0 */
package farf;

public interface EG2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTALIASSECTION = 2;
  public int JJTALIAS = 3;
  public int JJTMATCHERSSECTION = 4;
  public int JJTGLOBPATTERN = 5;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AliasSection",
    "Alias",
    "MatchersSection",
    "GlobPattern",
  };
}
/* JavaCC - OriginalChecksum=43866503a94e2f075c6d65270c5b7293 (do not edit this line) */
