/* Generated By:JJTree&JavaCC: Do not edit this line. EG2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 7;
  /** RegularExpression Id. */
  int IN = 8;
  /** RegularExpression Id. */
  int MAPTO = 9;
  /** RegularExpression Id. */
  int NI = 10;
  /** RegularExpression Id. */
  int ALIASES = 11;
  /** RegularExpression Id. */
  int MATCHERS = 12;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 13;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 14;
  /** RegularExpression Id. */
  int HEX_LITERAL = 15;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int FQCN = 20;
  /** RegularExpression Id. */
  int METHOD_GLOB = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"let\"",
    "\"in\"",
    "\"->\"",
    "\"ni\"",
    "\"aliases\"",
    "\"matchers\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<FQCN>",
    "<METHOD_GLOB>",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
  };

}
