/* Generated By:JavaCC: Do not edit this line. EG2TreeConstants.java Version 5.0 */
public interface EG2TreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTALIASSECTION = 2;
  public int JJTALIAS = 3;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "AliasSection",
    "Alias",
  };
}
/* JavaCC - OriginalChecksum=039b27e4f76c870a0583c7ba61594eed (do not edit this line) */
